INDEX_COLS:
- date
- economy
- measure
- vehicle_type
- unit
- medium
- transport_type
- drive
- fuel
- frequency
- scope
concordances_file_path: './input_data/concordances/9th/model_concordances_measures_20230717.csv'
#in the below, make sure to set the key to be as much of the file name as you can while excluding its date . this willk be searched for using utility_functions.get_latest_date_for_data_file(folder, KEY) 
datasets:
  thailand_new_stocks_9th_model_first_iteration_:
    file_path: intermediate_data/THA/thailand_new_stocks_9th_model_first_iteration_FILE_DATE_ID.csv
    folder: intermediate_data/THA/
    script: grooming_code\1_import_9th_modelled_data.py
    included: True
    type: transport
  usa_new_stocks_9th_model_first_iteration_:
    file_path: intermediate_data/USA/usa_new_stocks_9th_model_first_iteration_FILE_DATE_ID.csv
    folder: intermediate_data/USA/
    script: grooming_code\1_import_9th_modelled_data.py
    included: True
    type: transport
  ATO_data_cleaned_:
    file_path: intermediate_data/ATO/ATO_data_cleaned_FILE_DATE_ID.csv
    folder: intermediate_data/ATO/
    script: 2_clean_ATO_data.py
    included: True
    type: transport
  ATO_data_cleaned_car_not_ldv_:
    file_path: intermediate_data/ATO/ATO_data_cleaned_car_not_ldv_FILE_DATE_ID.csv
    folder: intermediate_data/ATO/
    script: 2_clean_ATO_data.py
    included: False
    type: transport
  ATO_revenue_pkm:
    file_path: intermediate_data/estimated/ATO_revenue_pkmFILE_DATE_ID.csv
    folder: intermediate_data/estimated/
    script: 2_clean_ATO_data.py
    included: True
    type: transport
  EGEDA_9th_cleaned_:
    file_path: intermediate_data/EGEDA/model_input_9th_cleanedFILE_DATE_ID.csv
    folder: intermediate_data/EGEDA/
    script: 1_extract_cleansed_EGEDA_data.py
    included: False
    type: transport
  EGEDA_9th_cleaned_split_into_transport_types:
    file_path: intermediate_data/estimated/EGEDA_9th_cleaned_split_into_transport_typesFILE_DATE_ID.csv
    folder: intermediate_data/estimated/
    script: split_egeda_cleansed_into_transport_types.py
    included: True
    type: transport
  EGEDA_split_into_transport_types:
    file_path: intermediate_data/estimated/EGEDA_split_into_transport_typesFILE_DATE_ID.csv
    folder: intermediate_data/estimated/
    script: split_egeda_into_transport_types.py
    included: False
    type: transport
  _8th_ATO_bus_update.csv:
    file_path: ./intermediate_data/estimated/FILE_DATE_ID_8th_ATO_bus_update.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: False #removed because not unique enough
    type: transport
  _8th_ATO_passenger_road_updates.csv:
    file_path: ./intermediate_data/estimated/FILE_DATE_ID_8th_ATO_passenger_road_updates.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: False #removed because not unique enough
    type: transport
  _8th_ATO_road_freight_tonne_km.csv:
    file_path: ./intermediate_data/estimated/FILE_DATE_ID_8th_ATO_road_freight_tonne_km.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: False #removed because not unique enough
    type: transport
  _8th_ATO_vehicle_type_update.csv:
    file_path: ./intermediate_data/estimated/FILE_DATE_ID_8th_ATO_vehicle_type_update.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: False #removed because not unique enough
    type: transport
  _8th_iea_ev_all_stock_updates.csv:
    file_path: intermediate_data/estimated/FILE_DATE_ID_8th_iea_ev_all_stock_updates.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: False #removed because not unique enough
    type: transport
  _evs.csv:
    file_path: intermediate_data/IEA/FILE_DATE_ID_evs.csv
    folder: intermediate_data/IEA/
    script: 1_clean_iea_ev_data.py 
    included: True
    type: transport
  _iea_fuel_economy.csv:
    file_path: intermediate_data/IEA/FILE_DATE_ID_iea_fuel_economy.csv
    folder: intermediate_data/IEA/
    script: 1_clean_iea_fuel_economy.py
    included: True
    type: transport
  _turnover_rate_3pct:
    file_path: intermediate_data/estimated/FILE_DATE_ID_turnover_rate_3pct.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: True
    type: transport
  all_macro_data_:
    file_path: intermediate_data/Macro/all_macro_data_FILE_DATE_ID.csv
    folder: intermediate_data/Macro/
    script: TBA
    included: True
    type: other
  eigth_edition_transport_data_final_:
    file_path: intermediate_data/8th_edition_transport_model/eigth_edition_transport_data_final_FILE_DATE_ID.csv
    folder: intermediate_data/8th_edition_transport_model/
    script: 3_make_extra_changes_to_8th_data.py
    included: False
    type: transport
  eigth_edition_transport_data_final_new_vtypes_drives_:
    file_path: intermediate_data/8th_edition_transport_model/eigth_edition_transport_data_final_new_vtypes_drives_FILE_DATE_ID.csv
    folder: intermediate_data/8th_edition_transport_model/
    script: 4_make_8th_data_for_new_vtypes.py
    included: True
    type: transport
  item_dataset_clean_:
    file_path: intermediate_data/item_data/item_dataset_clean_FILE_DATE_ID.csv
    folder: intermediate_data/item_data/
    script: 1_clean_item_data.py
    included: True
    type: transport
  missing_drive_values_:
    file_path: intermediate_data/estimated/filled_missing_values/missing_drive_values_FILE_DATE_ID.csv
    folder: intermediate_data/estimated/filled_missing_values/
    script: fill_missing_drive_values.py
    included: True
    type: transport
  nearest_available_date:
    file_path: intermediate_data/estimated/nearest_available_dateFILE_DATE_ID.csv
    folder: intermediate_data/estimated/
    script: TBA
    included: False
    type: transport
  mileage_occupancy_load_efficiency_data_:
    file_path: intermediate_data/estimated/mileage_occupancy_load_efficiency_data_FILE_DATE_ID.csv
    folder: intermediate_data/estimated/
    script: aggregate_best_estimate_efficiency_occupancy_load_mileage.py
    included: False
    type: transport
  manually_inputted_data_cleaned_road:
    file_path: intermediate_data/estimated/manually_inputted_data_cleaned_roadFILE_DATE_ID.csv
    folder: intermediate_data/estimated
    script: grooming_code/1_groom_manually_inputted_data.py
    included: True
    type: transport
  manually_inputted_data_cleaned_other:
    file_path: intermediate_data/estimated/manually_inputted_data_cleaned_otherFILE_DATE_ID.csv
    folder: intermediate_data/estimated
    script: grooming_code/1_groom_manually_inputted_data.py
    included: True
    type: transport
  USA_based_vehicle_efficiency_estimates:
    file_path: intermediate_data/estimated/USA_based_vehicle_efficiency_estimates_FILE_DATE_ID.csv
    folder: intermediate_data/estimated/
    script: insert_gathered_efficiency_data.py
    included: True
    type: transport
  

  